contact_links:
  - name: 💡 Feature Request
    url: https://github.com/sunjingyun/pkg/discussions/new
    about: Share ideas for new features
  - name: ❓ Question
    url: https://github.com/sunjingyun/pkg/discussions/new
    about: General questions